language: objective-c
osx_image: xcode10.1

cache:
  directories:
    - Carthage

addons:
  homebrew:
    packages:
    - carthage
    - swiftlint
    update: true

install:
  - gem install xcpretty
  - gem install xcpretty-travis-formatter

before_script:
  - carthage bootstrap --platform iOS --cache-builds --no-use-binaries

script:
  - swiftlint
  - xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`; exit ${PIPESTATUS[0]}

env:
  global:
    - TMPDIR=/tmp
    - secure: TE3fUfG6hDKvCO6DneXa0P5KBzej9cgsYsGbmt5wBoNrpE29af1V892lmweBM7ZflZx07HiUWI52o3dcb5c97VY0EgCc4Sj0gEsM/ie3kcU4AVVbZ+YAMMKg6FedE5X8bPyDC4zgKEqYGa/nTVZJhzt7gXpemOR7kgt2LvapysWHpN/N+zcT5JtJ2BiwcBzDo6cfj9aEMPc73D4fmSIrSl8VTOI/Xb+hiRX1C/EPd1idDASO8rwo0yDkDKyp9qFl0F2MVrkWdDDcNJ50T5k37WzbfEW9GBuibOoIfoMNQls2FdFb0RJu9N79skP4e/HqDKGHQz04aSBjctMbfAvMLvCf3v/LNQkjcrjn8hs/2uLBpt0pca+LGJI+cwo3tLtegZ9gYw6NlyoON2oB/D3IT5TrjETCF4KRKmZQU5LidZ2vkrBvXTIDTmnPfAfYZxA4uP5y3/n762msFWAZdm+zFpNp7gESBISut0iRLDUC5GXodyEsefJEoO0nC4XavcprNUGEa3xaiZHRNU1aKC6/xj2ImAq4RA5+ObzlOdm/4fj6yg2sYMZg1kY08rCn3LYp0tyP1+2BrwLcOgEljBd0ghitvv9XTz87m7gKi/gbFEVwZHd7PWNds/oin+baECU6VTB8OXNSH9Yq83di1jw72onkro9J/UW0v+jWLeo4xk8=

after_failure:
  - cat $TMPDIR/carthage-*.log

